lib.path = "main.rs"

[package]
name = "uboot-riscv64-rt"
description = """
uboot-riscv64-rt
"""
version = "0.0.0"

license = "Apache-2.0"
edition = "2021"

[dependencies]
riscv-rt = { git = "https://github.com/mekosko/riscv.git", features = [
  "s-mode",
  "u-boot",
] }
