[package]
name = "morojenoye"
description = """
morojenoye
"""
version = "0.0.0"

license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "morojenoye"
path = "main.rs"

[target.'cfg(target_arch = "riscv64")'.dependencies]
uboot-riscv64-rt = { path = "../uboot-riscv64-rt" }
